AWSTemplateFormatVersion: 2010-09-09
Description: Create AWS config recorder

Parameters:
  RecorderName:
    Type: String
    Default: default
    Description: Name of the Config recorder
  BucketName:
    Type: String
    Description: S3 bucket ARN for delivery of config items

Resources:

  DefaultConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: !Ref RecorderName
      RoleARN: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/config.amazonaws.com/AWSServiceRoleForConfig
      RecordingGroup:
        AllSupported: false
        IncludeGlobalResourceTypes: false
        RecordingStrategy:
          UseOnly: INCLUSION_BY_RESOURCE_TYPES
        ResourceTypes:
          - AWS::IAM::User
          - AWS::IAM::Group
          - AWS::IAM::Role
          - AWS::S3::Bucket
          - AWS::ACM::Certificate

  DefaultDeliveryChannelS3:
    Type: AWS::Config::DeliveryChannel
    Properties:
      Name: default
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Six_Hours
      S3BucketName: !Ref BucketName
      S3KeyPrefix: anewprefix
